[package]
name = "randomart"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clearscreen = { version = "2.0.1", features = ["windows-console"] }
rand = "0.8.5"
termsize = "0.1.6"
